[[language]]
name = "php"
auto-format = true
language-servers = [ "intelephense" ]

[language-server.intelephense]
command = "intelephense"
args = ["--stdio"]
config = { storagePath = "/tmp/intelephense" }
# Add your source folders here so it scans them
includePaths = ["."] 

[[language]]
name = "vue"
auto-format = true
language-servers = [ "vue-language-server" ]

[language-server.vue-language-server]
command = "vue-language-server"
args = ["--stdio"]
# CRITICAL FIX: Point explicitly to the tsserver library
config = { typescript = { tsdk = "/opt/homebrew/lib/node_modules/typescript/lib" } }

